/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.regna.calculatricemavenjunit;

import fr.regna.calculatricemavenjunit.entity.Number;
import javax.swing.JButton;

/**
 *
 * @author etudiant
 */
public class CalculatorMavenJUnit extends javax.swing.JFrame {

    static Number numberOne = new Number(0); // Nombre 1
    static Number numberTwo = new Number(0); // Nombre 2
    static double resultat = 0; // Résultat de l'opération

    static String event = "init"; // Enregistre l'étape actuelle parmis les différents processus
    static String operation = ""; // L'opération à faire
    static String expression = ""; // Sauvegarde le calcul
    static String numberString = ""; // Variable temporaire pour définir les nombres (1&2)

    /**
     * Creates new form CalculatorMavenGit
     */
    public CalculatorMavenJUnit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldAffichage = new javax.swing.JTextField();
        buttonClear = new javax.swing.JButton();
        buttonPoint = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        buttonDiviser = new javax.swing.JButton();
        buttonMultiplier = new javax.swing.JButton();
        buttonSoustraire = new javax.swing.JButton();
        buttonAdditionner = new javax.swing.JButton();
        buttonEgale = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textFieldAffichage.setEditable(false);
        textFieldAffichage.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        textFieldAffichage.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldAffichage.setText("0");
        textFieldAffichage.setFocusable(false);

        buttonClear.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        buttonClear.setText("clear");
        buttonClear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear(evt);
            }
        });

        buttonPoint.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        buttonPoint.setText(".");
        buttonPoint.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point(evt);
            }
        });

        button0.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        button0.setText("0");
        button0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number(evt);
            }
        });

        button1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        button1.setText("1");
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number(evt);
            }
        });

        button2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        button2.setText("2");
        button2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number(evt);
            }
        });

        button3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        button3.setText("3");
        button3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number(evt);
            }
        });

        button4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        button4.setText("4");
        button4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number(evt);
            }
        });

        button5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        button5.setText("5");
        button5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number(evt);
            }
        });

        button6.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        button6.setText("6");
        button6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number(evt);
            }
        });

        button7.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        button7.setText("7");
        button7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number(evt);
            }
        });

        button8.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        button8.setText("8");
        button8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number(evt);
            }
        });

        button9.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        button9.setText("9");
        button9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number(evt);
            }
        });

        buttonDiviser.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        buttonDiviser.setText("/");
        buttonDiviser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonDiviser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operation(evt);
            }
        });

        buttonMultiplier.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        buttonMultiplier.setText("*");
        buttonMultiplier.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonMultiplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operation(evt);
            }
        });

        buttonSoustraire.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        buttonSoustraire.setText("-");
        buttonSoustraire.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonSoustraire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operation(evt);
            }
        });

        buttonAdditionner.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        buttonAdditionner.setText("+");
        buttonAdditionner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonAdditionner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operation(evt);
            }
        });

        buttonEgale.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        buttonEgale.setText("=");
        buttonEgale.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonEgale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEgaleAction(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textFieldAffichage)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonDiviser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonMultiplier, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonSoustraire, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(buttonAdditionner, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(button0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(buttonEgale, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(textFieldAffichage, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDiviser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMultiplier, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSoustraire, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAdditionner, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(buttonEgale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEgaleAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEgaleAction
        // TODO add your handling code here:
        calculer();
    }//GEN-LAST:event_buttonEgaleAction

    private void operation(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operation
        // TODO add your handling code here:
        JButton button = (JButton) evt.getSource();
        setOperation(button);
    }//GEN-LAST:event_operation

    private void number(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number
        // TODO add your handling code here:
        JButton button = (JButton) evt.getSource();
        setNumber(button.getText());
    }//GEN-LAST:event_number

    private void clear(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_clear

    private void point(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point
        // TODO add your handling code here:
        decimal();
    }//GEN-LAST:event_point

    /* -------- Mes fonctions --------*/
    private void calculer() {
        event = "resultat";

        if (!"".equals(operation) && numberOne.getNumber() != 0 && numberTwo.getNumber() != 0) {

            double nbOne = numberOne.getNumber();
            double nbTwo = numberTwo.getNumber();

            switch (operation) { // Savoir quelle opération à faire selon le choix de l'utilisateur
                case "+":
                    resultat = nbOne + nbTwo;
                    break;
                case "-":
                    resultat = nbOne - nbTwo;
                    break;
                case "*":
                    resultat = nbOne * nbTwo;
                    break;
                case "/":
                    resultat = nbOne / nbTwo;
                    break;
            }
            afficher();
        }
    }

    private void setOperation(JButton button) {
        if (!"resultat".equals(event)) {
            event = "operation";
            operation = button.getText(); // Récupère l'opération à faire
            numberString = ""; // Permettre de récupérer par la suite la saisie pour le nombre 2
            afficher();
        }

    }

    private void setNumber(String number) {

        if (!"resultat".equals(event)) {

            numberString = numberString + number;

            if (operation.equals("")) { // Si l'opération n'a pas encore été choisi alors l'utilisateur saisi le nombre 1
                if ("point".equals(event)) {
                    numberOne.setDecimal(numberString);
                } else {
                    numberOne.setValue(Integer.parseInt(numberString));
                }
                System.out.println("Nombre_1 : " + numberOne.getNumber());
            } else { // Si l'utilisateur a choisi l'opération à réaliser alors il saisit le nombre 2
                if ("point".equals(event)) {
                    numberTwo.setDecimal(numberString);
                } else {
                    numberTwo.setValue(Integer.parseInt(numberString));
                }
                System.out.println("Nombre_2 : " + numberTwo.getNumber());
            }

            afficher();
        }
    }

    private void decimal() {
        if (!"point".equals(event) && !"resultat".equals(event)) {
            event = "point";
            numberString = "";
        }
    }

    private void reset() {
        event = "init";

        numberOne.setNumber(0);
        numberTwo.setNumber(0);
        resultat = 0;
        operation = "";
        numberString = "";

        afficher();
    }

    private void afficher() {

        expression = "";

        if (numberOne.getNumber() != 0) {
            expression = expression + numberOne.getNumber();
        }
        if (!"".equals(operation)) {
            expression = expression + operation;
        }

        if (numberTwo.getNumber() != 0) {
            expression = expression + numberTwo.getNumber();
        }

        if (resultat != 0) {
            expression = "" + resultat;
        }

        textFieldAffichage.setText(expression);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorMavenJUnit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorMavenJUnit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorMavenJUnit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorMavenJUnit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorMavenJUnit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonAdditionner;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDiviser;
    private javax.swing.JButton buttonEgale;
    private javax.swing.JButton buttonMultiplier;
    private javax.swing.JButton buttonPoint;
    private javax.swing.JButton buttonSoustraire;
    private javax.swing.JTextField textFieldAffichage;
    // End of variables declaration//GEN-END:variables
}
